### ISSUE TITLE
How to handle null values in graphs

### ISSUE THREAD

**Issue by SimonHoenscheid** [puppetlabs/puppet_operational_dashboards#113] opened 2022-11-24 10:10 UTC
## Use Case
currently the dashboards interpolates times if there are no metrics. In my opinion this can lead to false interpretation from a viewers perspective. 

You can see this pretty well in the screenshot. But it is not always this clear:

<img width="1710" alt="puppetserver_interpolated_metrics" src="https://user-images.githubusercontent.com/4162281/203753577-0a70a1eb-2a21-4fd2-a286-0a4f6f3da652.PNG">

## Describe the Solution You Would Like
reconfigure the dashboards, so graphas are not interpolating null values.

## Describe Alternatives You've Considered
Keep it as is

**Comment by m0dular** [comment] 2022-12-06 22:12
I think it would be good to have a configurable parameter for this, since some people may want to connect nulls and some may not.  But, I honestly haven't figured out how to turn it off.  I've tried every combination of `fill()` in the queries, as well as the "Connect null values" option in the dashboards, but it always connects them.

I don't know if this is an issue with a specific versions of InfluxDB and Grafana, how the queries and dashboards are written, or something else, but it always connects nulls for me.  If someone can figure it out I'll gladly accept that contribution.

**Comment by SimonHoenscheid** [comment] 2022-12-08 12:32
There are some open bugs right now in grafana, which prevent this behaviour. I will add these later.

**Comment by SimonHoenscheid** [comment] 2022-12-09 09:33
I just followed the issues. It starts with https://github.com/grafana/grafana/issues/42993 and the last one I could find was https://github.com/grafana/grafana/pull/50988, which was part of grafana 9.0.1.

**Comment by m0dular** [comment] 2023-02-23 21:23
We looked into this more, and the issue is that there are no `nulls` in the database, just a lack of data points.  Grafana can only connect or not connect if there are `null` values inserted, so we would have to do something like catch errors in collection and insert nulls when they happen.  If the node or `telegraf` service is shut down, I don't think there is an option for doing so.  I'll close this one for now since it's more of a feature than a Grafana config issue.

**Closed by m0dular** 2023-02-23 21:23 UTC
Labels: enhancement
